# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52e24c73321de31311619fe740b29ac4dfae2bf315bef43965a67fa557c276981f00ae9796e56b362228a65f0630d58a47a6aba79531d25491f19cbfb50ec6e1

test:
  secret_key_base: 8c0ba77303d3f12747bff309f3add8d40a833b1fe0255b1352c14e4636648bb3660f37328527d443a547490ba41a7f17264a7d8d1a093adca346ef42d3e76a0d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
